default: &default
  hostname: localhost
  port: 8983
  path: /solr/default
development:
  <<: *default
  path: /solr/development
test:
  <<: *default
  port: 8982
  path: /solr/test
production:
  <<: *default
  port: 8080
  path: /solr/honeycomb
